CONFIGURATION = {
    'weights': {
        'title': 0.7,
        'body': 0.3
    },
    'path_documents': 'data/docs',
    'path_data': 'data',
    'file_index': 'data/index.bin',
    'file_parse': 'data/parse.bin',
    'file_drop': 'data/minors.bin',
    'file_unigram_lm': 'data/uni_lm.bin',
    'file_bigram_lm': 'data/bi_lm.bin',
    'hyper_parameters': {
        'k1': 1.2,
        'b': 0.75,
        'landa': 0.9
    },
    'docs_count_lim': 10,
    'prob_lim': 0.0001,
    'batches_count': 10
}

STOP_WORDS = [
    '؟',
    '?',
    ':',
    'و',
    'در',
    'به',
    'از',
    'که',
    'می',
    'این',
    'است',
    'را',
    'با',
    'های',
    'برای',
    'تا',
    'ای',
    'بر',
    'بود',
    'کند',
    'هم',
    'یا',
    'نمی',
    'آن',
    'ان',
    'شود',
    'شده',
    'خود',
    'کرد',
    'شد',
    'بود',
    'گفت',
    'چه',
    'هر',
    'اما',
    'ما',
    'شما',
    'تو',
    'من',
    'او',
    'همه',
    '»',
    '«'
]